# Generated by Django 4.1.5 on 2023-02-20 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checking', 'проверка наличия (склад)'), ('compliance', 'проверка логистического соответствия'), ('loading', 'погрузка'), ('return', 'возврат')], default='checking', max_length=256, verbose_name='статус заказа')),
                ('number', models.CharField(max_length=256, verbose_name='номер заказа')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='цена')),
                ('customers_name', models.CharField(max_length=256, verbose_name='имя заказчика')),
                ('customers_phone', models.CharField(max_length=256, verbose_name='номер телефона заказчика')),
                ('date', models.DateField(verbose_name='конечная дата заказа')),
                ('delivery_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='цена доставки')),
                ('delivery_position', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='позиция погрузки')),
                ('order_comment', models.TextField(blank=True, null=True, verbose_name='комментарий заказа')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='main.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
            ],
            options={
                'verbose_name': 'источник заказа',
                'verbose_name_plural': 'источники заказов',
            },
        ),
        migrations.CreateModel(
            name='StatusStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checking', 'проверка наличия (склад)'), ('compliance', 'проверка логистического соответствия'), ('loading', 'погрузка'), ('return', 'возврат')], max_length=256, verbose_name='статус заказа')),
                ('order_comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_story', to='main.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'история статуса',
                'verbose_name_plural': 'история статусов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='main.source', verbose_name='источник заказа'),
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='количество')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='main.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='CheckingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы - проверка наличия (склад)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.order',),
        ),
        migrations.CreateModel(
            name='ComplianceOrder',
            fields=[
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы - проверка логистического соответствия',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.order',),
        ),
        migrations.CreateModel(
            name='LoadingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы - погрузка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.order',),
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы - возврат',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.order',),
        ),
    ]
