# Generated by Django 4.1.5 on 2023-02-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checking', 'проверка наличия (склад)'), ('compliance', 'проверка логистического соответствия'), ('loading', 'погрузка'), ('return', 'возврат')], default='checking', max_length=256, verbose_name='статус заказа')),
                ('number', models.IntegerField(verbose_name='номер заказа')),
                ('source', models.CharField(max_length=256, verbose_name='источник заказа')),
                ('date', models.DateField(verbose_name='конечная дата заказа')),
                ('delivery_price', models.PositiveIntegerField(default=0, verbose_name='цена доставки')),
                ('delivery_position', models.SmallIntegerField(default=0, verbose_name='позиция погрузки')),
                ('order_comment', models.TextField(blank=True, verbose_name='адрес заказа')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='цена')),
                ('customers_name', models.CharField(max_length=256, verbose_name='имя заказчика')),
                ('customers_phone', models.CharField(max_length=256, verbose_name='номер телефона заказчика')),
                ('address', models.CharField(max_length=256, verbose_name='адрес заказа')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='StatusStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checking', 'проверка наличия (склад)'), ('compliance', 'проверка логистического соответствия'), ('loading', 'погрузка'), ('return', 'возврат')], max_length=256, verbose_name='статус заказа')),
                ('order_comment', models.TextField(verbose_name='адрес заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_story', to='main.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'история статуса',
                'verbose_name_plural': 'история статусов',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='количество')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='main.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
