# Generated by Django 4.1.5 on 2023-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentOrder',
            fields=[
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы - отправлено',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.order',),
        ),
        migrations.AddField(
            model_name='element',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='вес (кг)'),
        ),
        migrations.AddField(
            model_name='order',
            name='logic_slots',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='кол-во логистических мест'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('checking', 'проверка наличия (склад)'), ('compliance', 'проверка логистического соответствия'), ('loading', 'погрузка'), ('return', 'возврат'), ('sent', 'отправлено')], default='checking', max_length=256, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='statusstory',
            name='status',
            field=models.CharField(choices=[('checking', 'проверка наличия (склад)'), ('compliance', 'проверка логистического соответствия'), ('loading', 'погрузка'), ('return', 'возврат'), ('sent', 'отправлено')], max_length=256, verbose_name='статус заказа'),
        ),
    ]
