# Generated by Django 4.1.5 on 2023-02-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_source_alter_order_order_comment_alter_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_position',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='позиция погрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='цена доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='цена'),
        ),
    ]
