# Generated by Django 4.1.5 on 2023-03-04 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sentorder_element_weight_order_logic_slots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkingorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы - проверка наличия (склад)'},
        ),
        migrations.AlterModelOptions(
            name='complianceorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы - проверка логистического соответствия'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='loadingorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы - погрузка'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='returnorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы - возврат'},
        ),
        migrations.AlterModelOptions(
            name='sentorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы - отправлено'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Источник заказа', 'verbose_name_plural': 'Источники заказов'},
        ),
        migrations.AlterModelOptions(
            name='statusstory',
            options={'verbose_name': 'История статуса', 'verbose_name_plural': 'История статусов'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='element',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='element',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='main.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='element',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='main.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customers_name',
            field=models.CharField(max_length=256, verbose_name='Имя заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customers_phone',
            field=models.CharField(max_length=256, verbose_name='Номер телефона заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Конечная дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_position',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Позиция погрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logic_slots',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во логистических мест'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=256, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='main.source', verbose_name='Источник заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('checking', 'Проверка наличия (склад)'), ('compliance', 'Проверка логистического соответствия'), ('loading', 'Погрузка'), ('return', 'Возврат'), ('sent', 'Отправлено')], default='checking', max_length=256, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='statusstory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_story', to='main.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='statusstory',
            name='order_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='statusstory',
            name='status',
            field=models.CharField(choices=[('checking', 'Проверка наличия (склад)'), ('compliance', 'Проверка логистического соответствия'), ('loading', 'Погрузка'), ('return', 'Возврат'), ('sent', 'Отправлено')], max_length=256, verbose_name='Статус заказа'),
        ),
    ]
