# Generated by Django 4.1.5 on 2023-02-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_delivery_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=256, verbose_name='номер заказа'),
        ),
    ]
