# Generated by Django 4.1.5 on 2023-03-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_checkingorder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы в работе',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.order',),
        ),
    ]
