# Generated by Django 4.1.5 on 2023-03-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_workorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkingorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Проверка наличия (склад)'},
        ),
        migrations.AlterModelOptions(
            name='complianceorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Проверка логистического соответствия'},
        ),
        migrations.AlterModelOptions(
            name='loadingorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Погрузка'},
        ),
        migrations.AlterModelOptions(
            name='returnorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Возврат'},
        ),
        migrations.AlterModelOptions(
            name='sentorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Отправлено'},
        ),
    ]
