# Generated by Django 4.1.5 on 2023-02-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы - проверка наличия (склад)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.order',),
        ),
        migrations.CreateModel(
            name='ComplianceOrder',
            fields=[
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы - проверка логистического соответствия',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.order',),
        ),
        migrations.CreateModel(
            name='LoadingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы - погрузка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.order',),
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы - возврат',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.order',),
        ),
    ]
