# Generated by Django 4.1.5 on 2023-03-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_checkingorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='element',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='Адрес заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа от'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа до'),
        ),
    ]
