# Generated by Django 4.1.5 on 2023-02-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_checkingorder_complianceorder_loadingorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusstory',
            name='order_comment',
            field=models.TextField(blank=True, null=True, verbose_name='адрес заказа'),
        ),
    ]
