# Generated by Django 4.1.5 on 2023-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_date_from_alter_order_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
