# Generated by Django 4.1.5 on 2023-03-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_element_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkingorder',
            options={'verbose_name': 'Заказ проверка наличия (склад)', 'verbose_name_plural': 'Проверка наличия (склад)'},
        ),
        migrations.AlterModelOptions(
            name='complianceorder',
            options={'verbose_name': 'Заказ проверка логистического соответствия', 'verbose_name_plural': 'Проверка логистического соответствия'},
        ),
        migrations.AlterModelOptions(
            name='loadingorder',
            options={'verbose_name': 'Заказ погрузка', 'verbose_name_plural': 'Погрузка'},
        ),
        migrations.AlterModelOptions(
            name='returnorder',
            options={'verbose_name': 'Заказ возврат', 'verbose_name_plural': 'Возврат'},
        ),
        migrations.AlterModelOptions(
            name='sentorder',
            options={'verbose_name': 'Заказ отправлено', 'verbose_name_plural': 'Отправлено'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name': 'Заказ в работе', 'verbose_name_plural': 'Заказы в работе'},
        ),
    ]
