# Generated by Django 4.1.5 on 2023-03-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_departure_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_complaint',
            field=models.BooleanField(default=False, verbose_name='Рекламация'),
        ),
    ]
